"""groups_db_change

Revision ID: 166a49c87c7a
Revises: 
Create Date: 2023-11-07 15:26:48.347738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166a49c87c7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups_data', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('groups_data', sa.Column('group', sa.Integer(), nullable=False))
    op.add_column('groups_data', sa.Column('subgroup', sa.Integer(), nullable=False))
    op.add_column('groups_data', sa.Column('reg_date', sa.DATE(), nullable=True))
    op.create_unique_constraint(None, 'groups_data', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups_data', type_='unique')
    op.drop_column('groups_data', 'reg_date')
    op.drop_column('groups_data', 'subgroup')
    op.drop_column('groups_data', 'group')
    op.drop_column('groups_data', 'user_id')
    # ### end Alembic commands ###
