"""1_0_0

Revision ID: 1a84a01974d1
Revises: 
Create Date: 2023-11-14 20:28:41.856603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a84a01974d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_presidents',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lessons_data',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subgroup', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(), nullable=False),
    sa.Column('lesson_type', sa.VARCHAR(length=2), nullable=False),
    sa.Column('teacher_short_name', sa.String(), nullable=False),
    sa.Column('lesson_time_start', sa.VARCHAR(length=5), nullable=False),
    sa.Column('lesson_date_start', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'lesson_name', 'lesson_time_start', 'lesson_date_start')
    )
    op.create_table('lessons_links',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(), nullable=False),
    sa.Column('lesson_type', sa.VARCHAR(length=2), nullable=False),
    sa.Column('teacher_short_name', sa.String(), nullable=False),
    sa.Column('lesson_link', sa.String(), nullable=False),
    sa.Column('add_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('group_id', 'lesson_name', 'lesson_type', 'teacher_short_name')
    )
    op.create_table('students_data',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('subgroup', sa.Integer(), nullable=False),
    sa.Column('notify', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('jetiq', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('visits_data',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits_data')
    op.drop_table('students_data')
    op.drop_table('lessons_links')
    op.drop_table('lessons_data')
    op.drop_table('class_presidents')
    # ### end Alembic commands ###
