version: '3.8'
services:
  db:
    image: postgres:latest
    env_file:
      - ./bot/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "127.0.0.1:5423:5423"
    command: -p 5423
  bot:
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - ./bot/.env
    restart: always
    depends_on:
      - db

volumes:
  pgdata: